export * from './home.resolver';
export * from './asistencias.resolver';
export * from './centros.resolver';
export * from './cursos.resolver';
export * from './materias.resolver';
export * from './notificaciones.resolver';
export * from './profesores.resolver';
export * from './users.resolver';
export * from './administradores.resolver';