import { User } from './user.model';
import { Solution } from './solution.model';

export interface OpportunityProposal {
    _id?: string,
    estimatedTotal?: number,
    thLicenses: number,
    ckLicenses: number,
    newLicenses: boolean,
    needConsulting: boolean,
    newThLicenses: number,
    newCkLicenses: number,
    notes: string,
    totalHours: number,
    isChosenProposal: boolean,
    contractDuration: number,
    digitization_docTypes: number,
    digitization_avFieldsDocType: number,
    digitization_autoRecognition: boolean,
    digitization_autoRecognitionDocs: number,
    digitization_docsPdfTextLayer: boolean,
    digitization_docsBarcode: boolean,
    digitization_extractDocsData: boolean,
    digitization_avExtractFields: boolean,
    docManager_docsClasses: number,
    docManager_avFieldsDocClass: number,
    docManager_storageLogic: boolean,
    automation_workflows: number,
    automation_avStatesWorkflow: number,
    automation_monitors: number,
    automation_groups: number,
    automation_prototypes: number,
    implementation_type: string,
    implementation_adIntegration: boolean,
    implementation_adminsTraining: boolean,
    chosenSolution: any,
    solutionQuestions: any,
    usedConstants: any,
    createdAt: Date,
    createdBy: User,
    modifiedAt: Date,
    modifiedBy: User,
}